services:
  - type: web
    name: s3haim
    runtime: node
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=8192
