export {
  MOBILE_CONTEXT_MENU_OVERLAY_CLASS,
  MOBILE_CONTEXT_MENU_PANEL_CLASS,
  MOBILE_CONTEXT_MENU_ITEM_CLASS,
  MOBILE_CONTEXT_MENU_DANGER_ITEM_CLASS,
  MOBILE_CONTEXT_MENU_DISMISS_GUARD_MS,
  MOBILE_CONTEXT_MENU_POINTER_BLOCK_MS,
} from '../shared/contextMenu/mobileContextMenuStyles';
