export type {
  PrintChromeDoc,
  PrintChromeImageTemplate,
  PrintChromeNumbering,
  PrintChromePageNumberTemplate,
  PrintChromePlacement,
  PrintChromePosition,
  PrintChromeTemplate,
  PrintChromeTemplateBase,
  PrintChromeTextTemplate,
} from '@/utils/printChrome/types';

export {
  DEFAULT_PRINT_CHROME_DOC,
  DEFAULT_PRINT_CHROME_PAGE_NUMBER_FORMAT,
  PRINT_CHROME_FONT_SIZE_MAX,
  PRINT_CHROME_FONT_SIZE_MIN,
  PRINT_CHROME_IMAGE_SIZE_MAX,
  PRINT_CHROME_IMAGE_SIZE_MIN,
  PRINT_CHROME_POSITIONS,
  PRINT_CHROME_POSITION_LABELS,
  applyPrintChromePlacementToAll,
  applyPrintChromePlacementToPage,
  clampPrintChromePlacement,
  createDefaultImageTemplate,
  createDefaultPageNumberTemplate,
  createDefaultTextTemplate,
  createPrintChromeId,
  printChromePageKey,
  resolvePrintChromePlacement,
} from '@/utils/printChrome/types';

export {
  escapePrintChromeJsonForComment,
  formatPrintChromePageLabel,
  isPrintChromeLeadingMetaRegion,
  normalizePrintChromeDoc,
  parsePrintChrome,
  rebuildLeadingMeta,
  resolvePrintChromePageNumber,
  serializePrintChromeComment,
  shouldPersistPrintChrome,
  stripPrintChromeComment,
  unescapePrintChromeJsonFromComment,
  upsertPrintChromeComment,
  type ParsePrintChromeResult,
} from '@/utils/printChrome/parse';
