import { createContext } from 'react';

/** Modal open flags + modal-only handlers (not vault/file/tree domain). */
export type AppModalsValue = {
  showSaveMethodModal: boolean;
  setShowSaveMethodModal: (v: boolean) => void;
  saveMethodModalCreds: any;
  setSaveMethodModalCreds: (v: any) => void;
  webauthnPRFSupported: boolean;
  handleSaveWithWebAuthn: (...args: any[]) => any;
  handleSaveWithPasswordFromModal: (...args: any[]) => any;
  showSetPasswordModal: boolean;
  setShowSetPasswordModal: (v: boolean) => void;
  masterPassword: string;
  requestSaveEncryptedSettings: (...args: any[]) => any;
  s3Creds: any;
  showCoverChangeConfirmModal: boolean;
  setShowCoverChangeConfirmModal: (v: boolean) => void;
  pendingCoverSaveRef: { current: any };
  showRestoreLocalFolderModal: boolean;
  setShowRestoreLocalFolderModal: (v: boolean) => void;
  pendingLocalFolderName: string;
  handleConfirmRestoreLocalFolder: (...args: any[]) => any;
  setLocalFolderRestoreSettled: (v: boolean) => void;
  showAppUpdateConfirmModal: boolean;
  setShowAppUpdateConfirmModal: (v: boolean) => void;
  appBuildLocalId: string;
  appBuildRemoteId: string | null;
  appUpdateCheckError: string | null;
  appUpdateAvailable: boolean;
  isApplyingPwaUpdate: boolean;
  handleConfirmAppUpdate: (...args: any[]) => any;
  showOverwriteCredsConfirmModal: boolean;
  setShowOverwriteCredsConfirmModal: (v: boolean) => void;
  handleOverwriteCredsConfirm: (...args: any[]) => any;
  setPendingWebAuthnSave: (v: any) => void;
  setPendingPasswordSave: (v: any) => void;
  showUnsavedConfirmModal: boolean;
  setShowUnsavedConfirmModal: (v: boolean) => void;
  handleUnsavedConfirmLeave: (...args: any[]) => any;
  showSuffixChangeConfirmModal: boolean;
  setShowSuffixChangeConfirmModal: (v: boolean | ((p: boolean) => boolean)) => void;
  setSuffixConfirmAction: (v: string | ((p: string) => string)) => void;
  handleSuffixChangeConfirm: (...args: any[]) => any;
  handleSuffixChangeCancel: (...args: any[]) => any;
  addToNoteSelectPath: any;
  setAddToNoteSelectPath: (v: any) => void;
  showCloseFileConfirmModal: boolean;
  setShowCloseFileConfirmModal: (v: boolean) => void;
  pendingCloseTabId: string | null;
  setPendingCloseTabId: (v: string | null) => void;
  handleCloseFileConfirmSave: (...args: any[]) => any;
  handleCloseFileConfirmDiscard: (...args: any[]) => any;
  navGuard: any;
  handleNavGuardConfirmSave: (...args: any[]) => any;
  handleNavGuardConfirmDiscard: (...args: any[]) => any;
  showExportPasswordModal: boolean;
  setShowExportPasswordModal: (v: boolean) => void;
  handleExportConfirm: (...args: any[]) => any;
  showImportPasswordModal: boolean;
  setShowImportPasswordModal: (v: boolean) => void;
  handleImportConfirm: (...args: any[]) => any;
  setImportFileContent: (v: any) => void;
  showDownloadMethodModal: boolean;
  setShowDownloadMethodModal: (v: boolean) => void;
  downloadModalMode: string;
  setDownloadModalMode: (v: string) => void;
  handleDownloadCurrentFile: (...args: any[]) => any;
  handleDownloadToFolder: (...args: any[]) => any;
  handleSelectHaimFromDownload: (...args: any[]) => any;
  handleCopyCurrentFileToClipboard: (...args: any[]) => any;
  downloadProgress: any;
  setDownloadProgress: (v: any) => void;
  downloadComplete: boolean;
  setDownloadComplete: (v: boolean) => void;
  showSaveSessionToNoteModal: boolean;
  setShowSaveSessionToNoteModal: (v: boolean) => void;
  newFileDefaultParentPath: string | null;
  isSavingSessionToNote: boolean;
  handleConfirmSaveSessionToNote: (...args: any[]) => any;
  saveSessionToNoteSelectPath: any;
  setSaveSessionToNoteSelectPath: (v: any) => void;
  downloadResultModal: any;
  closeDownloadResultModal: (...args: any[]) => any;
  associatedRecordings: any;
  confirmDelete: (...args: any[]) => any;
  confirmEmptyTrash: (...args: any[]) => any;
  handleConfirmMoveFileFromSidebar: (...args: any[]) => any;
  handleConfirmMove: (...args: any[]) => any;
  handleConfirmMoveFolder: (...args: any[]) => any;
  createModalTree: any;
  ensureCreateModalFolderLoaded: (...args: any[]) => any;
  handleCreateItemSubmit: (...args: any[]) => any;
};

export const AppModalsContext = createContext<AppModalsValue | null>(null);
