export type {
  ChatWorkspaceTab,
  ContentSearchWorkspaceTab,
  FileNoteSurface,
  FileStorageType,
  FileWorkspaceTab,
  LlmAssistWorkspaceTab,
  PersistedWorkspaceTab,
  PersistedWorkspaceTabs,
  PersistedWorkspaceTabsV1,
  SettingsWorkspaceTab,
  WorkspaceTab,
  WorkspaceTabsState,
} from '@/utils/workspaceTabs/types';
export {
  CHAT_TAB_ID,
  CONTENT_SEARCH_TAB_ID,
  EDITABLE_VIEWERS,
  LAST_FILE_KEY,
  LLM_ASSIST_TAB_ID,
  SETTINGS_TAB_ID,
  WORKSPACE_TABS_STORAGE_KEY,
  WORKSPACE_TAB_SOFT_CAP,
  defaultWorkspaceLayout,
  isEditableViewer,
} from '@/utils/workspaceTabs/types';
export type {
  PaneLeaf,
  PaneNode,
  PaneSplit,
  PaneSplitEdge,
  PersistedPaneNode,
  SplitLeafResult,
} from '@/utils/workspaceTabs/paneLayout';
export {
  WORKSPACE_PANE_SOFT_CAP,
  WORKSPACE_TAB_GROUP_ZONE_ID,
  WORKSPACE_TAB_ORPHAN_ZONE_ID,
  PANE_SPLIT_RATIO_MIN,
  PANE_SPLIT_RATIO_MAX,
  collectLeaves,
  countLeaves,
  createEmptyLeaf,
  createSingleLeafLayout,
  findLeaf,
  findLeafContainingTab,
  flattenTabIdsFromLayout,
  fromPersistedPaneNode,
  getFocusedLeafActiveId,
  isPaneLeaf,
  isPaneSplit,
  listOrphanTabIds,
  pruneLayoutToTabs,
  applyPersistedLayoutMembership,
  syncLayoutPreservingOrphansWhenSplit,
  syncLayoutWithTabs,
  toPersistedPaneNode,
  collapseLeafIntoSibling,
  splitLeaf,
  splitAtWorkspaceEdge,
} from '@/utils/workspaceTabs/paneLayout';
export {
  PANE_ALIGN_RATIO_EPSILON,
  collectLinkedAlignedSplitIds,
  findOrthogonalSiblingSplit,
  findSplit,
  normalizeAfterSnappedResize,
  normalizeAlignedTwoByTwo,
  resizeSplitLinked,
  syncSiblingSplitRatio,
  tryTransposeAlignedTwoByTwo,
} from '@/utils/workspaceTabs/paneLayoutNormalize';
export {
  anyFileTabDirty,
  createChatTab,
  createContentSearchTab,
  createFileTab,
  createLlmAssistTab,
  createSettingsTab,
  fileTabId,
  isChatTab,
  isContentSearchTab,
  isFileTab,
  isFileTabDirty,
  isLlmAssistTab,
  isSettingsTab,
  revokeFileTabObjectUrl,
  tabDirectoryPath,
  tabDisplayTitle,
} from '@/utils/workspaceTabs/helpers';
export {
  clearPersistedWorkspaceTabs,
  loadPersistedWorkspaceTabs,
  savePersistedWorkspaceTabs,
  toPersistedWorkspaceTabs,
} from '@/utils/workspaceTabs/persistence';
export {
  activateTab,
  clearExportPdfInLeaf,
  clearOrphanExportPdf,
  closeTab,
  collapsePaneLeaf,
  emptyWorkspaceTabsState,
  evictForSoftCap,
  extractTabToOrphan,
  findFileTab,
  getActiveFileTab,
  getActiveTab,
  moveTab,
  moveTabIntoLeaf,
  openExportPdfForTab,
  openExportPdfInLeaf,
  openOrActivateChat,
  openOrActivateContentSearch,
  openOrActivateLlmAssist,
  openOrActivateSettings,
  openOrReplaceFileTab,
  patchFileTab,
  replaceWorkspaceLayout,
  retargetFileTab,
  retargetFileTabsByPathPrefix,
  setFocusedPane,
  splitTabToEdge,
  splitTabToWorkspaceEdge,
  swapPanesOrMoveTabToCenter,
} from '@/utils/workspaceTabs/workspaceTabsStore';
export type { RetargetFileTabInput, OpenFileTabInput, SplitTabToEdgeResult } from '@/utils/workspaceTabs/workspaceTabsStore';
export {
  CLOSED_TAB_HISTORY_KEY,
  CLOSED_TAB_HISTORY_MAX,
  clearClosedTabHistory,
  closedTabEntryFromWorkspaceTab,
  closedTabHistoryLength,
  loadClosedTabHistory,
  popClosedTab,
  pushClosedTab,
  saveClosedTabHistory,
} from '@/utils/workspaceTabs/closedTabHistory';
export type { ClosedTabEntry } from '@/utils/workspaceTabs/closedTabHistory';
export {
  LAST_OPEN_TABS_RESTORE_KEY,
  TABS_RESTORE_QUEUE_KEY,
  clearLastOpenTabsSnapshot,
  clearTabsRestoreQueue,
  clearWorkspaceTabsForRestart,
  loadLastOpenTabsSnapshot,
  pickWorkspaceTabsRestoreSource,
  persistWorkspaceTabsForRestart,
  persistedTabId,
  persistedTabToClosedEntry,
  popTabsRestoreQueue,
  saveLastOpenTabsSnapshot,
  seedTabsRestoreQueueFromSnapshot,
  tabsRestoreQueueLength,
} from '@/utils/workspaceTabs/lastOpenTabsRestore';
export { routePaneEditorChange } from '@/utils/workspaceTabs/routePaneEditorChange';
