export {
  CHAT_FOLDER,
  SELF_GROUP,
  ADD_GROUP_VALUE,
  detectTimeZone,
  localDateString,
  formatMessageTime,
  formatMessageDateLabel,
  formatChatDayListLabel,
  formatMessageFileNameBase,
  chatImagePathPrefix,
  chatFilePathPrefix,
  groupIconPathPrefix,
  messageEditsFolder,
  messageEditVersionKey,
  messageEditVersionFileName,
  editVersionAtFromFileName,
} from '@/utils/chatWithMyself/paths.js';
export {
  parseDayFile,
  serializeMessage,
  appendMessageToContent,
  appendMessagesToContent,
  dedupeMessagesById,
  prependUniqueMessages,
  appendUniqueMessages,
  createMessageId,
  isSelfGroup,
  isChatMessageMarkdown,
  isChatMessageEncrypted,
  makeReplySnippet,
  formatChatMessageAsNoteMarkdown,
  formatChatMessagePlainText,
  formatChatMessageMarkdownCopy,
  parseChatWithMyselfNoteMeta,
  chatSavedNoteLinkTo,
  chatMessageHash,
  chatMessageUrl,
  noteViewHref,
  formatNoteShareChatBody,
  formatFolderShareChatBody,
  parseAppViewPath,
} from '@/utils/chatWithMyself/format.js';
export { normalizeSharePayload, sharePayloadFromSearch } from '@/utils/chatWithMyself/sharePayload.js';
export {
  hasShareSearchParams,
  hasShareTargetFlag,
  shareBodyFromSearch,
  readSharePromptFromWindow,
  loadShareTargetFiles,
  resolvePendingShareIntent,
  enqueuePendingShare,
  listPendingShares,
  removePendingShare,
  peekChoosePendingShare,
  claimComposePendingShares,
  flushSendSelfPendingShares,
  sharePromptHasContent,
  normalizeShareFiles,
} from '@/utils/chatWithMyself/pendingShares.js';
export { appendShareChatMessage } from '@/utils/chatWithMyself/shareSend.js';
export {
  canOpenShareFilesAsSession,
  filesForShareTargetSession,
  isShareTargetMarkdownFile,
  isShareTargetMarkdownMime,
  sessionOriginForShareTargetFiles,
} from '@/utils/chatWithMyself/shareTargetSession.js';
export { canOfferWebShare, shareChatMessage } from '@/utils/chatWithMyself/shareChatMessage.js';
export {
  SHARE_TARGET_CACHE,
  SHARE_TARGET_FLAG,
  SHARE_TARGET_FILE_PARAM,
  takeShareTargetFiles,
  storeShareTargetFiles,
} from '@/utils/chatWithMyself/shareTargetCache.js';
export {
  normalizeStoragePath,
  deletedNoteScopeFromNode,
  pathAffectedByDelete,
  messageNeedsNoteUnlink,
} from '@/utils/chatWithMyself/noteRefs.js';
export {
  extractUrls,
  splitTextWithUrls,
  isYouTubeUrl,
  fetchOpenGraph,
  parseOpenGraphHtml,
  fetchOgMetadata,
  loadAndArchiveOg,
  readCachedOg,
  refreshAndArchiveOg,
  reloadOgCache,
  reloadOgCacheForMessageBody,
  hashUrl,
} from '@/utils/chatWithMyself/og';
export {
  readMeta,
  writeMeta,
  touchTimezone,
  addGroup,
  setGroupIcon,
  renameGroup,
  normalizeGroups,
  sortGroupsKo,
  groupNames,
  groupIconMap,
  groupLabelMap,
  findGroup,
  resolveGroupLabel,
  resolveGroupId,
  groupMatches,
  createGroupId,
  stableGroupIdFromName,
  listDayKeys,
  readDayMessages,
  readDayFileParsed,
  appendChatMessage,
  appendChatMessages,
  deleteChatMessage,
  updateChatMessage,
  writeMessageEditVersion,
  listMessageEditVersionKeys,
  loadMessageEditHistoryPage,
  deleteMessageEditVersion,
  deleteMessageEditHistoryEntry,
  deleteAllMessageEditHistory,
  findMessageById,
  resolveReplyThreadMessages,
  patchChatMessageMeta,
  unlinkChatNotesForDeletedPaths,
  createOgStorageAdapters,
  readOgArchive,
  writeOgArchive,
  writeDayMessages,
  flushPendingMessages,
  createChatBackend,
} from '@/utils/chatWithMyself/storage.js';
export { mergeDayMessages, serializeDayFile, serializeDeletedMarker } from '@/utils/chatWithMyself/format.js';
export {
  ENCRYPTED_MESSAGE_LABEL,
  parseEncryptedChatPayload,
  encryptChatMessageBody,
  decryptChatMessageBody,
} from '@/utils/chatWithMyself/encryptedMessage.js';
export {
  parseReactionsAttr,
  serializeReactionsAttr,
  toggleReaction,
  hasReaction,
  reactionKey,
  normalizeReaction,
} from '@/utils/chatWithMyself/reactions.js';
export {
  postChatSyncEvent,
  postChatLocalSyncEvent,
  CHAT_SYNC_CHANNEL,
  CHAT_LOCAL_SYNC_EVENT,
  getChatSyncTabId,
} from '@/utils/chatWithMyself/syncChannel.js';
export { uploadChatImage, uploadGroupIcon, chatImagesToMarkdown } from '@/utils/chatWithMyself/images.js';
export { getCroppedImg, getCroppedImgFromPadMeta, fileFromCroppedCanvas } from '@/utils/chatWithMyself/cropImage.js';
export { serializeEditVersion, parseEditVersion } from '@/utils/chatWithMyself/editHistory.js';
export {
  uploadChatFile,
  uploadChatAttachment,
  chatAttachmentsToMarkdown,
  isChatImageFile,
  formatChatAttachmentSize,
  sanitizeChatFileMeta,
  parseChatFileToken,
  extractChatBodyAttachments,
  deleteChatAttachment,
} from '@/utils/chatWithMyself/attachments.js';
export {
  getCollectionMediaFlags,
  upsertCollectionMembership,
} from '@/utils/chatWithMyself/collectionScan.js';
export {
  fuzzyMatchText,
  splitSearchTokens,
  fuzzyMatchTokensInHaystacks,
  highlightHtmlMatches,
  renderSearchResultHtml,
  buildSearchPreviewText,
  buildSearchResultDisplayText,
  loadMessageOgSearchText,
  loadOgSearchText,
  ogDataToSearchText,
} from '@/utils/chatWithMyself/search.js';
export { reactionsToSearchText } from '@/utils/chatWithMyself/reactionSearch.js';
export { groupColor, isSelfGroupName } from '@/utils/chatWithMyself/groupAvatar.js';
export {
  COMPOSER_DRAFT_LS_KEY,
  readComposerDraftMeta,
  writeComposerDraftMeta,
  clearComposerDraft,
  syncComposerDraftImages,
  loadComposerDraftImageQueue,
  composerDraftHasContent,
} from '@/utils/chatWithMyself/composerDraft.js';
export { looksLikeMarkdown } from '@/utils/chatWithMyself/markdownDetect.js';
export {
  CHAT_TREE_ATTACH_DROPPABLE_ID,
  isChatTreeAttachDroppableId,
  collectFileNodesUnderFolder,
  listFilesUnderFolderPath,
  resolveTreeAttachFileNodes,
  buildTreeNoteShareBodies,
  buildTreeShareItems,
} from '@/utils/chatWithMyself/treeAttachDrop.js';
export {
  CHAT_PREF_PREFIX,
  CHAT_PREF_KEYS,
  defaultComposerToolbarVisible,
  readComposerToolbarPref,
  writeComposerToolbarPref,
  getComposerToolbarVisible,
  readComposerLineNumbersPref,
  writeComposerLineNumbersPref,
  getComposerLineNumbersVisible,
  readComposerHelperTextPref,
  writeComposerHelperTextPref,
  getComposerHelperTextVisible,
  readOpenLinksInNewWindowPref,
  writeOpenLinksInNewWindowPref,
  getOpenLinksInNewWindow,
  isSafariBrowser,
  defaultChatPerfReduceEnabled,
  readPerfReduceLayoutAnimPref,
  writePerfReduceLayoutAnimPref,
  getPerfReduceLayoutAnimEnabled,
  readPerfReduceBubblePressFxPref,
  writePerfReduceBubblePressFxPref,
  getPerfReduceBubblePressFxEnabled,
  readComposerLightweightPref,
  writeComposerLightweightPref,
  getComposerLightweightEnabled,
  readChatRailOpenPref,
  writeChatRailOpenPref,
  getChatRailOpen,
} from '@/utils/chatWithMyself/composerPrefs.js';
export {
  createPretextMeasurer,
  decideTabDensity,
  splitLabelChars,
} from '@/utils/chatWithMyself/tabPretext.js';
