/* eslint-disable @typescript-eslint/no-explicit-any -- App shell modal props bridge; tightened in Phase C */

export type AppModalsProps = {
  showSaveMethodModal: boolean;
  setShowSaveMethodModal: (v: boolean) => void;
  saveMethodModalCreds: any;
  setSaveMethodModalCreds: (v: any) => void;
  webauthnPRFSupported: boolean;
  handleSaveWithWebAuthn: (...args: any[]) => any;
  handleSaveWithPasswordFromModal: (...args: any[]) => any;
  showSetPasswordModal: boolean;
  setShowSetPasswordModal: (v: boolean) => void;
  masterPassword: string;
  requestSaveEncryptedSettings: (...args: any[]) => any;
  s3Creds: any;
  showCoverChangeConfirmModal: boolean;
  setShowCoverChangeConfirmModal: (v: boolean) => void;
  pendingCoverSaveRef: { current: any };
  saveFile: (...args: any[]) => any;
  currentFileRef: { current: any };
  editorContentRef: { current: any };
  setEditorContent: (v: string) => void;
  showRestoreLocalFolderModal: boolean;
  setShowRestoreLocalFolderModal: (v: boolean) => void;
  pendingLocalFolderName: string;
  handleConfirmRestoreLocalFolder: (...args: any[]) => any;
  setLocalFolderRestoreSettled: (v: boolean) => void;
  showAppUpdateConfirmModal: boolean;
  setShowAppUpdateConfirmModal: (v: boolean) => void;
  appBuildLocalId: string;
  appBuildRemoteId: string | null;
  appUpdateCheckError: string | null;
  appUpdateAvailable: boolean;
  isApplyingPwaUpdate: boolean;
  handleConfirmAppUpdate: (...args: any[]) => any;
  showOverwriteCredsConfirmModal: boolean;
  setShowOverwriteCredsConfirmModal: (v: boolean) => void;
  handleOverwriteCredsConfirm: (...args: any[]) => any;
  setPendingWebAuthnSave: (v: any) => void;
  setPendingPasswordSave: (v: any) => void;
  treeNameConflict: any;
  settleTreeNameConflict: (...args: any[]) => any;
  theme: string;
  showUnsavedConfirmModal: boolean;
  setShowUnsavedConfirmModal: (v: boolean) => void;
  handleUnsavedConfirmLeave: (...args: any[]) => any;
  showSuffixChangeConfirmModal: boolean;
  handleSuffixChangeConfirm: (...args: any[]) => any;
  handleSuffixChangeCancel: (...args: any[]) => any;
  showCloseFileConfirmModal: boolean;
  setShowCloseFileConfirmModal: (v: boolean) => void;
  pendingCloseTabId: string | null;
  setPendingCloseTabId: (v: string | null) => void;
  workspaceTabs: any;
  handleCloseFileConfirmSave: (...args: any[]) => any;
  handleCloseFileConfirmDiscard: (...args: any[]) => any;
  navGuard: any;
  handleNavGuardConfirmSave: (...args: any[]) => any;
  handleNavGuardConfirmDiscard: (...args: any[]) => any;
  showExportPasswordModal: boolean;
  setShowExportPasswordModal: (v: boolean) => void;
  handleExportConfirm: (...args: any[]) => any;
  showImportPasswordModal: boolean;
  setShowImportPasswordModal: (v: boolean) => void;
  handleImportConfirm: (...args: any[]) => any;
  setImportFileContent: (v: any) => void;
  showDownloadMethodModal: boolean;
  setShowDownloadMethodModal: (v: boolean) => void;
  downloadModalMode: string;
  setDownloadModalMode: (v: any) => void;
  currentFile: any;
  editorContent: string;
  handleDownloadCurrentFile: (...args: any[]) => any;
  handleDownloadToFolder: (...args: any[]) => any;
  handleSelectHaimFromDownload: (...args: any[]) => any;
  handleCopyCurrentFileToClipboard: (...args: any[]) => any;
  downloadProgress: number;
  setDownloadProgress: (v: number) => void;
  downloadComplete: boolean;
  setDownloadComplete: (v: boolean) => void;
  showSaveSessionToNoteModal: boolean;
  setShowSaveSessionToNoteModal: (v: boolean) => void;
  storageMode: string;
  s3Tree: any;
  localTree: any;
  webdavTree: any;
  localRootHandle: any;
  newFileDefaultParentPath: string;
  isSavingSessionToNote: boolean;
  handleConfirmSaveSessionToNote: (...args: any[]) => any;
  setCreateModalContext: (v: any) => void;
  setCreateModalOpen: (v: boolean) => void;
  saveSessionToNoteSelectPath: any;
  setSaveSessionToNoteSelectPath: (v: any) => void;
  downloadResultModal: any;
  closeDownloadResultModal: (...args: any[]) => any;
  deleteTarget: any;
  setDeleteTarget: (v: any) => void;
  associatedRecordings: any;
  confirmDelete: (...args: any[]) => any;
  isDeleting: boolean;
  emptyTrashTarget: any;
  setEmptyTrashTarget: (v: any) => void;
  isEmptyingTrash: boolean;
  confirmEmptyTrash: (...args: any[]) => any;
  isMoveModalOpen: boolean;
  setIsMoveModalOpen: (v: boolean) => void;
  moveFileTarget: any;
  setMoveFileTarget: (v: any) => void;
  moveModalSelectPath: any;
  setMoveModalSelectPath: (v: any) => void;
  handleConfirmMoveFileFromSidebar: (...args: any[]) => any;
  handleConfirmMove: (...args: any[]) => any;
  moveFolderTarget: any;
  setMoveFolderTarget: (v: any) => void;
  handleConfirmMoveFolder: (...args: any[]) => any;
  createModalOpen: boolean;
  createModalContext: any;
  createModalTree: any;
  ensureCreateModalFolderLoaded: (...args: any[]) => any;
  isCreateSubmitting: boolean;
  handleCreateItemSubmit: (...args: any[]) => any;
  encMdPrompt: any;
};


export type ExportPdfGateProps = {
  documentValue: string;
  documentFile: any;
  openCoverEdit: boolean;
  isDocumentLoading: boolean;
  hasNavigationSession: boolean;
  storageMode: string;
  localTree: any;
  webdavTree: any;
  s3Tree: any;
  openAdvancedSearchFile: (...args: any[]) => any;
  snippetConfig: any;
  showAuthModal: boolean;
  shareBlockingAuth: boolean;
  handleUnlock: (...args: any[]) => any;
  fileInputRef: any;
  proceedWithoutStoredCreds: (...args: any[]) => any;
  openSettingsWorkspaceTab: (...args: any[]) => any;
  canUnlockWithWebAuthnForModal: boolean;
  handleUnlockWithWebAuthn: (...args: any[]) => any;
  autoPromptWebAuthnForModal: boolean;
};
